### ISSUE TITLE
Refer to Sustainability Tier Docs references

### ISSUE THREAD

**Issue by mjohnson518** [protocol/green_scores#5]
Let's work to change the **Refer to Sustainability Tier Docs** references

<img width="1316" alt="Screen Shot 2023-02-02 at 12 22 56" src="https://user-images.githubusercontent.com/44822571/216323765-ee7c5b01-5a5c-4776-998d-6709499398a7.png">

**Comment by mjohnson518** [comment]
@niemacodes can you check [49a3c42](https://github.com/protocol/green_scores/commit/49a3c42ac81b205bebd55bcbfebb5cbb111b1b06) and if all looks good let's redeploy?

**Comment by niemacodes** [comment]
Looks just, just redeployed! Changes are live ^-^, much thanks!
